version: '3.8'

services:
  # Single-node Redis for basic testing
  redis:
    image: redis:7-alpine
    container_name: redis-bloom-test
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  # Pre-built Redis Cluster for distributed testing
  redis-cluster:
    image: grokzen/redis-cluster:7.0.4
    container_name: redis-cluster
    environment:
      - REDIS_CLUSTER_CREATOR=true
      - REDIS_CLUSTER_REPLICAS=1
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7000", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Test runner service
  test:
    image: golang:1.22
    container_name: bloom-test
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      redis:
        condition: service_healthy
      redis-cluster:
        condition: service_healthy
    command: go test -tags=integration -v ./bloom
    networks:
      - default

networks:
  default:
    name: redis-bloom-network 